server:
  port: 8080
  context-path: demo-service

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false

jwt:
  secret: zdtlD3JK56m6wTTgsNFhqzjqP
  jwtIssuer: kyawbobo


springdoc:
  api-docs.enabled: true
  api-docs.path: /rest-api-docs
  swagger-ui.path: /swagger-ui